// @safe-bluegreen - колонка только добавляется, старый цвет её не читает
import { type MigrateDownArgs, type MigrateUpArgs, sql } from '@payloadcms/db-sqlite';

/*
  Ступени оформления заменены одним полем со своим стилем: владелец пишет CSS,
  а не выбирает из наших слов. Приходит одна колонка.

  Прежние пять остаются в базе нетронутыми. Выкладка идёт двумя цветами, и во
  время прогона старый ещё обслуживает сайт: удаление колонки переписывает
  таблицу целиком и требует базу в одни руки - прогон падает на замке, а с ним
  и выкладка. Убирает их отдельная правка, когда старого цвета уже нет.

  Каждая правка идёт по факту: список таблиц у блока свой на каждом сайте -
  он зависит от того, где блок разрешили ставить, - и слепой ALTER TABLE
  завалил бы весь прогон на первой же недостающей таблице.
*/

async function hasColumn(db: MigrateUpArgs['db'], table: string, column: string) {
  const rows = await db.all(sql.raw(`PRAGMA table_info(\`${table}\`)`));
  return (rows as Array<{ name: string }>).some((row) => row.name === column);
}

async function hasTable(db: MigrateUpArgs['db'], table: string) {
  const rows = await db.all(
    sql.raw(`SELECT name FROM sqlite_master WHERE type='table' AND name='${table}'`),
  );
  return (rows as unknown[]).length > 0;
}

async function dropIfExists(db: MigrateUpArgs['db'], table: string, column: string) {
  if (!(await hasTable(db, table))) return;
  if (!(await hasColumn(db, table, column))) return;
  await db.run(sql.raw(`ALTER TABLE \`${table}\` DROP COLUMN \`${column}\`;`));
}

async function addIfMissing(db: MigrateUpArgs['db'], table: string, column: string) {
  if (!(await hasTable(db, table))) return;
  if (await hasColumn(db, table, column)) return;
  await db.run(sql.raw(`ALTER TABLE \`${table}\` ADD \`${column}\` text;`));
}

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await addIfMissing(db, '_pages_v_blocks_achievement_banner', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_articles_section', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_banner_slider', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_block_showcase', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_built_with', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_carousel', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_certified_notice', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_comparison_table', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_cta_banner', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_custom_markup', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_demo_access', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_document_list', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_faq_accordion', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_feature_grid', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_hero', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_hero_cinematic', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_hero_split', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_install_snippet', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_page_ref', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_project_types_grid', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_prose', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_quote', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_request_form', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_reusable_ref', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_rich_text', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_social_feed', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_specialist_directory', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_specialist_profile', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_stack_transparency', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_threads_section', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_timeline', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_video', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_video_set', 'appearance_css');
  await addIfMissing(db, '_pages_v_blocks_wave_divider', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_achievement_banner', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_articles_section', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_banner_slider', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_block_showcase', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_built_with', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_carousel', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_certified_notice', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_comparison_table', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_cta_banner', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_custom_markup', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_demo_access', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_document_list', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_faq_accordion', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_feature_grid', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_hero', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_hero_cinematic', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_hero_split', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_install_snippet', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_project_types_grid', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_prose', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_quote', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_request_form', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_rich_text', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_social_feed', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_specialist_directory', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_specialist_profile', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_stack_transparency', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_threads_section', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_timeline', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_video', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_video_set', 'appearance_css');
  await addIfMissing(db, '_reusable_blocks_v_blocks_wave_divider', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_achievement_banner', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_articles_section', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_banner_slider', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_block_showcase', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_built_with', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_carousel', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_certified_notice', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_comparison_table', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_cta_banner', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_custom_markup', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_demo_access', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_document_list', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_faq_accordion', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_feature_grid', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_hero', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_hero_cinematic', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_hero_split', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_install_snippet', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_page_ref', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_project_types_grid', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_prose', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_quote', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_request_form', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_reusable_ref', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_rich_text', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_social_feed', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_specialist_directory', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_specialist_profile', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_stack_transparency', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_threads_section', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_timeline', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_video', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_video_set', 'appearance_css');
  await addIfMissing(db, 'pages_blocks_wave_divider', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_achievement_banner', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_articles_section', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_banner_slider', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_block_showcase', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_built_with', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_carousel', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_certified_notice', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_comparison_table', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_cta_banner', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_custom_markup', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_demo_access', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_document_list', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_faq_accordion', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_feature_grid', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_hero', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_hero_cinematic', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_hero_split', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_install_snippet', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_project_types_grid', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_prose', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_quote', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_request_form', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_rich_text', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_social_feed', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_specialist_directory', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_specialist_profile', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_stack_transparency', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_threads_section', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_timeline', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_video', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_video_set', 'appearance_css');
  await addIfMissing(db, 'reusable_blocks_blocks_wave_divider', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_achievement_banner', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_articles_section', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_banner_slider', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_block_showcase', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_built_with', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_carousel', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_certified_notice', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_comparison_table', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_cta_banner', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_custom_markup', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_demo_access', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_document_list', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_faq_accordion', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_feature_grid', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_hero', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_hero_cinematic', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_hero_split', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_install_snippet', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_page_ref', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_project_types_grid', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_prose', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_quote', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_request_form', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_reusable_ref', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_rich_text', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_social_feed', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_specialist_directory', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_specialist_profile', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_stack_transparency', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_threads_section', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_timeline', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_video', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_video_set', 'appearance_css');
  await addIfMissing(db, 'specialists_blocks_wave_divider', 'appearance_css');
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await dropIfExists(db, '_pages_v_blocks_achievement_banner', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_articles_section', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_banner_slider', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_block_showcase', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_built_with', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_carousel', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_certified_notice', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_comparison_table', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_cta_banner', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_custom_markup', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_demo_access', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_document_list', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_faq_accordion', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_feature_grid', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_hero', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_hero_cinematic', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_hero_split', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_install_snippet', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_page_ref', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_project_types_grid', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_prose', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_quote', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_request_form', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_reusable_ref', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_rich_text', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_social_feed', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_specialist_directory', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_specialist_profile', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_stack_transparency', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_threads_section', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_timeline', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_video', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_video_set', 'appearance_css');
  await dropIfExists(db, '_pages_v_blocks_wave_divider', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_achievement_banner', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_articles_section', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_banner_slider', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_block_showcase', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_built_with', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_carousel', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_certified_notice', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_comparison_table', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_cta_banner', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_custom_markup', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_demo_access', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_document_list', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_faq_accordion', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_feature_grid', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_hero', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_hero_cinematic', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_hero_split', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_install_snippet', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_project_types_grid', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_prose', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_quote', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_request_form', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_rich_text', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_social_feed', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_specialist_directory', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_specialist_profile', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_stack_transparency', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_threads_section', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_timeline', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_video', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_video_set', 'appearance_css');
  await dropIfExists(db, '_reusable_blocks_v_blocks_wave_divider', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_achievement_banner', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_articles_section', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_banner_slider', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_block_showcase', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_built_with', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_carousel', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_certified_notice', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_comparison_table', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_cta_banner', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_custom_markup', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_demo_access', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_document_list', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_faq_accordion', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_feature_grid', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_hero', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_hero_cinematic', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_hero_split', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_install_snippet', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_page_ref', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_project_types_grid', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_prose', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_quote', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_request_form', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_reusable_ref', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_rich_text', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_social_feed', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_specialist_directory', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_specialist_profile', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_stack_transparency', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_threads_section', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_timeline', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_video', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_video_set', 'appearance_css');
  await dropIfExists(db, 'pages_blocks_wave_divider', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_achievement_banner', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_articles_section', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_banner_slider', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_block_showcase', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_built_with', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_carousel', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_certified_notice', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_comparison_table', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_cta_banner', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_custom_markup', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_demo_access', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_document_list', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_faq_accordion', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_feature_grid', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_hero', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_hero_cinematic', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_hero_split', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_install_snippet', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_project_types_grid', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_prose', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_quote', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_request_form', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_rich_text', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_social_feed', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_specialist_directory', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_specialist_profile', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_stack_transparency', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_threads_section', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_timeline', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_video', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_video_set', 'appearance_css');
  await dropIfExists(db, 'reusable_blocks_blocks_wave_divider', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_achievement_banner', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_articles_section', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_banner_slider', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_block_showcase', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_built_with', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_carousel', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_certified_notice', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_comparison_table', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_cta_banner', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_custom_markup', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_demo_access', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_document_list', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_faq_accordion', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_feature_grid', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_hero', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_hero_cinematic', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_hero_split', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_install_snippet', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_page_ref', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_project_types_grid', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_prose', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_quote', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_request_form', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_reusable_ref', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_rich_text', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_social_feed', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_specialist_directory', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_specialist_profile', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_stack_transparency', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_threads_section', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_timeline', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_video', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_video_set', 'appearance_css');
  await dropIfExists(db, 'specialists_blocks_wave_divider', 'appearance_css');
}
